"""empty message

Revision ID: 32489c6c8725
Revises: 77b97caba7f5
Create Date: 2019-05-17 00:03:26.322665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32489c6c8725'
down_revision = '77b97caba7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'timestamp')
    # ### end Alembic commands ###
