"""empty message

Revision ID: 6547d2c00e72
Revises: 344f87eed7f3
Create Date: 2019-04-22 21:50:40.132245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6547d2c00e72'
down_revision = '344f87eed7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'timestamp')
    # ### end Alembic commands ###
