"""empty message

Revision ID: c6e6c7153c74
Revises: 6547d2c00e72
Create Date: 2019-04-27 18:00:15.759000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e6c7153c74'
down_revision = '6547d2c00e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('kind', sa.String(), nullable=True))
    op.create_index(op.f('ix_card_kind'), 'card', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_kind'), table_name='card')
    op.drop_column('card', 'kind')
    # ### end Alembic commands ###
