"""empty message

Revision ID: f1b532cf6347
Revises: 11828f79822d
Create Date: 2019-04-27 22:50:37.735355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b532cf6347'
down_revision = '11828f79822d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_card_kind', table_name='card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_card_kind', 'card', ['kind'], unique=False)
    # ### end Alembic commands ###
