"""empty message

Revision ID: fa835f8ddb83
Revises: 32489c6c8725
Create Date: 2019-05-26 14:15:58.041654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa835f8ddb83'
down_revision = '32489c6c8725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('kind', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_card_kind'), 'card', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_kind'), table_name='card')
    op.drop_column('card', 'kind')
    # ### end Alembic commands ###
